version: '3.8'

networks:
  caffis-network:
    driver: bridge

volumes:
  pgdata:
  redis_data:

services:
  db:
    image: postgres:15-alpine
    container_name: caffis-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: caffis_user
      POSTGRES_PASSWORD: admin5026
      POSTGRES_DB: caffis_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - caffis-network

  backend:
    build: ./server
    container_name: caffis-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
      - "5555:5555"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - DATABASE_URL=postgresql://caffis_user:admin5026@db:5432/caffis_db
      - JWT_SECRET=caffis_jwt_secret_2024_super_secure_key_xY9mN3pQ7rT2wK5vL8bC
      - EMAIL_HOST=smtp.gmail.com
      - EMAIL_PORT=587
      - EMAIL_USER=alisadeghian7077@gmail.com
      - EMAIL_PASS=azwnegwuffgubzzg
      - EMAIL_FROM=Caffis <alisadeghian7077@gmail.com>
      - VERIFICATION_CODE_EXPIRY_MINUTES=5
      - MAX_VERIFICATION_ATTEMPTS=3
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      - db
    networks:
      - caffis-network
    command: ["node", "app.js"]

  frontend:
    build: ./client
    container_name: caffis-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - NEXT_PUBLIC_API_URL=http://localhost:5000
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - caffis-network
    command: ["npm", "run", "dev"]

  map-redis:
    image: redis:7-alpine
    container_name: caffis-map-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - caffis-network

  map-backend:
    build: ./caffis-map-service/backend
    container_name: caffis-map-backend
    restart: unless-stopped
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=development
      - PORT=5001
      - REDIS_HOST=map-redis
      - REDIS_PORT=6379
      - JWT_SECRET=caffis_jwt_secret_2024_super_secure_key_xY9mN3pQ7rT2wK5vL8bC
      - FRONTEND_URL=http://localhost:3000
      - MAIN_API_URL=http://backend:5000
      - MAPBOX_ACCESS_TOKEN=sk.eyJ1IjoiYWxpczIwMDEiLCJhIjoiY21jdGJ2anhiMDBhdjJtc2tmZ3l6cDJoZiJ9.cKgVNa3LFwSTGXmVFunDlg
      - ./caffis-map-service/backend:/app
      - /app/node_modules
    depends_on:
      - map-redis
      - backend
    networks:
      - caffis-network
    command: ["node", "src/server.js"]

  map-frontend:
    build: ./caffis-map-service/frontend
    container_name: caffis-map-frontend
    restart: unless-stopped
    ports:
      - "3002:3001"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_MAP_API_URL=http://localhost:5001
      - REACT_APP_MAPBOX_TOKEN=sk.eyJ1IjoiYWxpczIwMDEiLCJhIjoiY21jdGJ2anhiMDBhdjJtc2tmZ3l6cDJoZiJ9.cKgVNa3LFwSTGXmVFunDlg
    volumes:
      - ./caffis-map-service/frontend:/app
      - /app/node_modules
    depends_on:
      - map-backend
    networks:
      - caffis-network
