FROM node:18-alpine

# Install dependencies for Prisma
RUN apk add --no-cache python3 make g++ curl

WORKDIR /app

# Copy package files
COPY package*.json ./
COPY prisma ./prisma/

# Install dependencies
RUN npm install

# Generate Prisma client
RUN npx prisma generate

EXPOSE 5000 5555

# Use nodemon for hot reload
CMD ["npm", "run", "dev"]
